---

- hosts: kubeworkers
  become: true
  tasks:

  - name: Update Repository Index and Packages
    tags: kubernetes,piserver,update
    package:
      update_cache: yes
      name: "*"
      state: latest
