---

- hosts: all, !tomcatservers
  become: true
  pre_tasks:

  - name: Update Repository Index and Packages
    package:
      update_cache: yes
      name: "*"
      state: latest
    changed_when: false

- hosts: all
  become: true
  roles:
    - base

- hosts: webservers
  become: true
  roles:
    - web

- hosts: dbservers
  become: true
  roles:
    - database

- hosts: piserver
  become: true
  roles:
    - raspi

- hosts: tomcatservers
  become: true
  roles:
    - tomcat

- hosts: fileservers
  become: true
  roles:
    - file
