---

- hosts: all
  become: true
  pre_tasks:

  - name: Update Repository Index and Packages
    package:
      update_cache: yes
      name: "*"
      state: latest
    changed_when: false

- hosts: all
  become: true
  roles:
    - base
  tags: base

- hosts: piserver
  become: true
  roles:
    - raspi
  tags: raspi

- hosts: noteserver
  become: true
  roles:
    - noteserver
  tags: noteserver

- hosts: pimaster1
  become: true
  roles:
    - pimaster1
  tags: pimaster1

- hosts: kubeworkers
  become: true
  roles:
    - kubeworkers
  tags: kubeworkers
