---

- hosts: all
  become: true
  pre_tasks:

  - name: Update Repository Index and Packages
    package:
      update_cache: yes
      name: "*"
      state: latest
    changed_when: false

- hosts: all
  become: true
  roles:
    - base

- hosts: piserver
  become: true
  roles:
    - raspi

- hosts: noteserver
  become: true
  roles:
    - noteserver

- hosts: pimaster1
  become: true
  roles:
    - pimaster1

- hosts: kubeworkers
  become: true
  roles:
    - kubeworkers
