- name: Install MariaDB package (CentOS)
  yum:
    name: mariadb
    state: latest
  when: ansible_distribution == "CentOS"

- name: Install MariaDB package (Debian)
  apt:
    name: mariadb-server
    state: latest
  when: ansible_distribution == "Debian"
