- name: Install Apache package (CentOS)
    yum:
      name: httpd
      state: latest
    when: ansible_distribution == "CentOS"

- name: Start httpd (CentOS)
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_distribution == "CentOS"
