---

- hosts: webservers
  become: true
  tasks:

  - name: Copy default.html file for WebServer
    tags: apache2, apache, httpd
    remote_user: web
    copy:
      src: ~/ansible_homelab/manage-files/default.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

