- name: Create bind user in Debian-based
  tags: user, debian
  user:
    name: bind
    groups: sudo
    shell: /bin/bash
    create_home: yes
  when: ansible_os_family == "Debian"

- name: Add sudoers file for bind
  tags: user, no-password
  copy:
    src: "{{ bind_sudoers_file }}"
    dest: /etc/sudoers.d/bind
    owner: root
    group: root
    mode: 0440
