- name: Install Unzip package
  package:
    name: unzip
    state: latest


- name: Install Terraform
  unarchive:
    src: https://releases.hashicorp.com/terraform/1.9.0/terraform_1.9.0_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes
    owner: root
    group: root
    mode: 0755
