---

- hosts: all
  become: true
  tasks:

  - name: Update Repository Index in CentOS
    dnf:
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: Upgrade Packages in CentOS
    dnf:
      name: "*"
      state: latest
    when: ansible_distribution == "CentOS"

  - name: Update Repository Index in Debian
    apt:
      update_cache: yes
    when: ansible_distribution == "Debian"

  - name: Upgrade Packages in Debian
    apt:
      upgrade: dist
    when: ansible_distribution == "Debian"
