- name: Install Apache and PHP package (Ubuntu)
  tags: apache,php,ubuntu
  package:
    name:
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: latest

- name: Start and Enable Apache (Ubuntu)
  tags: apache,service,ubuntu
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes

- name: Change Email address for Admin
  tags: apache, config
  lineinfile:
    path: /etc/apache2/apache2.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin somebody@somewhere.com
  notify: restart_apache
